### ISSUE TITLE
New authentication required for activating lock

### ISSUE THREAD

**Issue by tim427** [lwestenberg/bold_smart_lock#6]
Hi @lwestenberg ,

I figured out the API requires a `Authorization: Bearer <TOKEN>` instead of `X-Auth-Token: <TOKEN>` header.

Sent me a email (see my profile) if you need some assistance ;)

**Comment by lwestenberg** [comment]
Thanks for finding the issue. I will create an update of the package today.

**Comment by dreasvandonselaar** [comment]
The code is still using the legacy API instead of the new oAuth based authentication right?

**Comment by tim427** [comment]
> The code is still using the legacy API instead of the new oAuth based authentication right?

Correct!

**Comment by dreasvandonselaar** [comment]
(X-Auth-Token is used by older versions of the Bold app and still seems to work)

**Comment by lwestenberg** [comment]
The oAuth2 flow works much better, also on mobile it uses the Bold app to verify your oAuth2 request so you don't have to enter any validation codes etc. Would recommend to use that one. For now I will close this issue.
