### ISSUE TITLE
Wrong API URL and remote-activation call not working

### ISSUE THREAD

**Issue by skle** [lwestenberg/bold_smart_lock#8]
It seems the domain `api.sesamtechnology.com` has certificate issues. The following domain should be used: `api.boldsmartlock.com`. 
See the following line in const.py:
`API_URI = "https://api.sesamtechnology.com/v1/"`

Another issue is using the call to activate the lock. It returns the following error:
`{"message":"Authentication is possible but has failed or not yet been provided.","errorMessage":"Authentication is possible but has failed or not yet been provided."}`

Any idea what could be wrong? I've already updated the authorisation token. Retrieving the device list (using the _/effective-device-permissions_ endpoint) is working fine.

Thanks in advance for your help!

**Comment by hvw33** [comment]
Actually it looks like they changed the SSL certificate of the API service.
A simple guess landed me on https://api.boldsmartlock.com/v1/ what seams to work.
I did not tried yet to change it in the module code for further testing

**Comment by lwestenberg** [comment]
No need to. We are close to completing the first integration with an official oAuth2 connection between Bold and Home Assistant (via Nabucasa)
